name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up docker compose
        uses: docker/setup-qemu-action@v2
        with:
          node-version: 19
      - name: Copy .env.examples to .env
        run: cp ./1-integ-test/.env.example ./1-integ-test/.env
      - name: Run tests
        run: cd 1-integ-test && npm run test:integration
